POST http://localhost:3000/todo/
Content-Type: application/json

{
  "title": "Javascript class"
}

###

GET http://localhost:3000/todo

###

GET http://localhost:3000/todo/649ef6c66e6f87f4a613fd9c


###
PATCH http://localhost:3000/todo/649ef6c66e6f87f4a613fd9c
Content-Type: application/json

{
  "status": 1
}

###
DELETE http://localhost:3000/todo/6490c7f99aa0309d3bb4c8a7

###
GET http://localhost:3000/todo/status/completed

###
GET http://localhost:3000/todo/get/status?limit=3&status=0